# Generated by Django 6.1.1 on 2026-09-09 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employersleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=400)),
                ('howmany_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_taken', models.DateField()),
                ('end_leave', models.DateField()),
                ('status', models.CharField(choices=[('APPROVE', 'approve'), ('REQUESTED', 'requested'), ('CANCELLED', 'cancelled')], default='REQUESTED')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_relation', to='leave_user.employers')),
            ],
        ),
    ]
